version: '3' 
networks:
 kong-net:
  driver: bridge
services: 
  kong-database: 
    container_name: postgre
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    networks: 
      - kong-net
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: "kong:latest"
    command: "kong migrations bootstrap"
    restart: on-failure
    networks: 
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-database

  kong-gateway: 
    container_name: apigateway
    image: kong:latest
    restart: always
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    networks: 
      - kong-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
    
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - /data/db
    networks: 
      - kong-net

  zone-service:
    container_name: zone-service
    image: zone-service
    depends_on:
      - mongo
    env_file:
      - ./zone-service/.env
    volumes: 
      - /Users/phucht/Projects/ad-server/zone-service/src:/opt/app
    networks: 
      - kong-net
    ports:
      - "3001:3000"  

