apps:
- script: src/index.js
  args: []
  name: "drm-service"
  watch: false
  restart_delay: 3000
  log_file: logs/drm.log
  error_file: logs/drm.err
  out_file: logs/drm.out
  log_date_format: YYYY-MM-DD HH:mm Z
  exec_mode: cluster
  ignore_watch: [".idea", "node_modules", "logs", "client"]
  env:
    NODE_ENV: "production"
    PORT: 8083
  instances: 1